baseURL = "https://meditationhub.ga/"
languageCode = "en-us"
title = "Meditation App For Relaxing The Mind And Body"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  star = "stars"
  
Paginate = 20