backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "static/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "sessions" # Used in routes, e.g., /admin/collections/blog
    label: "Sessions" # Used in the UI
    folder: "content/sessions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter

      - {label: "Title", name: "title", widget: "string"}
      
      - {label: "slug", name: "slug", widget: "string"}
      
      - {label: "thumbnail", name: "thumbnail", widget: "string"}

      - {label: "time", name: "time", widget: "string"}

      - {label: "tags", name: "tags", widget: "list", default: ["Guided Meditation"]}

      - {label: "stars", name: "stars", widget: "list"}

      - {label: "youtubeId", name: "youtubeId", widget: "string"}

      - {label: "dis", name: "dis", widget: "text"}